name 'aws_machine'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aws_machine'
long_description 'Installs/Configures aws_machine'
version '0.1.0'
